let javascriptIsFun = true;
console.log(javascriptIsFun);
console.log(typeof javascriptIsFun);
console.log(typeof true);
console.log(typeof 32);
console.log(typeof "Adrita");
javascriptIsFun = "YES!";
console.log(javascriptIsFun);
console.log(typeof javascriptIsFun);
let year;
console.log(year);
console.log(typeof year);
year = 1989;
console.log(typeof year);
console.log(typeof null);
